version: '3.8'

services:
  # Firecrawl local - substitui a API externa
  firecrawl:
    image: mendableai/firecrawl:latest
    ports:
      - "3002:3002"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - paraguai_network

  # Redis para Firecrawl e cache do sistema
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - paraguai_network

  # MongoDB para armazenamento principal (NoSQL)
  mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: paraguai_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - paraguai_network

  # Aplicação principal (Flask web interface)
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FIRECRAWL_API_KEY=local-instance
      - FIRECRAWL_BASE_URL=http://firecrawl:3002
      - OPENROUTER_API_KEY=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
      - OPENROUTER_BASE_URL=https://openrouter.ai/api/v1
      - OPENROUTER_MODEL=cognitivecomputations/dolphin-mistral-24b-venice-edition:free
      - MONGO_URL=mongodb://admin:admin123@mongodb:27017/paraguai_db?authSource=admin
      - REDIS_URL=redis://redis:6379
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - redis
      - firecrawl
    networks:
      - paraguai_network

volumes:
  mongodb_data:
  redis_data:

networks:
  paraguai_network:
    driver: bridge